#!/usr/bin/env python3
"""生成01_download.ipynb"""
import json

nb = {
 "cells": [
  {"cell_type":"markdown","metadata":{},"source":["# P01：金融数据获取\n\n| 项目 | 内容 |\n","|------|------|\n","| 姓名 | 柯骋 |\n","| 学号 | 25210150 |\n","| 课程 | 数据分析与经济决策（ds2026） |\n","\n","---\n","\n","## 任务说明\n\n本 Notebook 完成以下数据获取任务：\n","1. 下载10只A股股票过去5年的后复权日度行情\n","2. 下载沪深300和中证500指数数据\n","3. 下载CPI和M2宏观指标\n","4. 获取10只股票的财务指标（ROE、净利润率）\n","5. 记录下载日志"]},
  {"cell_type":"code","metadata":{},"source":["import os\nimport time\nimport json\nimport pandas as pd\nimport akshare as ak\nfrom datetime import datetime\n\n# ==================== 创建目录结构 ====================\ndirs = [\n    'data/stock', 'data/index', 'data/macro', 'data/finance',\n    'data/clean', 'data/combined', 'output'\n]\nfor d in dirs:\n    os.makedirs(d, exist_ok=True)\nprint('目录结构创建完成！')"],"execution_count":None,"outputs":[]},
  {"cell_type":"markdown","metadata":{},"source":["---\n","## 1.1 下载10只股票行情数据\n\n选取10只A股，覆盖银行、汽车、房地产、白酒、能源、通讯6个行业。"]},
  {"cell_type":"code","metadata":{},"source":["# 股票列表\nstocks = [\n    {'code': '600036', 'name': '招商银行', 'industry': '银行'},\n    {'code': '601398', 'name': '工商银行', 'industry': '银行'},\n    {'code': '002594', 'name': '比亚迪',   'industry': '汽车'},\n    {'code': '601633', 'name': '长城汽车', 'industry': '汽车'},\n    {'code': '000002', 'name': '万科A',    'industry': '房地产'},\n    {'code': '600048', 'name': '保利发展', 'industry': '房地产'},\n    {'code': '600519', 'name': '贵州茅台', 'industry': '白酒'},\n    {'code': '000858', 'name': '五粮液',   'industry': '白酒'},\n    {'code': '601857', 'name': '中国石油', 'industry': '能源'},\n    {'code': '000063', 'name': '中兴通讯', 'industry': '通讯'},\n]\n\n# 保存股票信息\nstock_info = pd.DataFrame(stocks)\nstock_info.to_csv('data/stock/stock_info.csv', index=False, encoding='utf-8-sig')\nprint(f'共选取 {len(stocks)} 只股票，覆盖 {stocks[0][\"industry\"]}等 {len(set(s[\"industry\"] for s in stocks))} 个行业')"],"execution_count":None,"outputs":[]},
  {"cell_type":"code","metadata":{},"source":["# 下载日志初始化\nlog_file = 'download_log.txt'\nwith open(log_file, 'w', encoding='utf-8') as f:\n    f.write(f'# 数据下载日志 - 生成时间: {datetime.now().strftime(\"%Y-%m-%d %H:%M:%S\")}\\n\\n')\n\ndef log_download(status, name, detail=''):\n    \"\"\"记录下载日志\"\"\"\n    ts = datetime.now().strftime('%Y-%m-%d %H:%M:%S')\n    line = f'[{ts}] {status:8s} {name:20s} {detail}'\n    with open(log_file, 'a', encoding='utf-8') as f:\n        f.write(line + '\\n')\n    print(line)\n\nprint('下载日志初始化完成')"],"execution_count":None,"outputs":[]},
  {"cell_type":"code","metadata":{},"source":["# 下载股票行情数据\nstart_date = '20200101'\nend_date = '20260521'\n\nfor s in stocks:\n    code = s['code']\n    name = s['name']\n    fname = f'data/stock/stock_{code}.csv'\n    \n    # 如果已有数据则跳过\n    if os.path.exists(fname):\n        df_exist = pd.read_csv(fname)\n        log_download('SKIP', f'stock_{code}', f'shape={df_exist.shape} (已存在)')\n        continue\n    \n    try:\n        time.sleep(1)  # 控制频率\n        df = ak.stock_zh_a_hist(\n            symbol=code, period='daily',\n            start_date=start_date, end_date=end_date,\n            adjust='hfq'  # 后复权\n        )\n        # 统一列名\n        df.columns = ['日期', '开盘价', '收盘价', '最高价', '最低价', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']\n        df = df[['日期', '开盘价', '收盘价', '最高价', '最低价', '成交量', '成交额']]\n        df.to_csv(fname, index=False, encoding='utf-8-sig')\n        log_download('SUCCESS', f'stock_{code}', f'shape={df.shape}')\n    except Exception as e:\n        log_download('FAILED', f'stock_{code}', f'Error: {str(e)[:60]}')\n\nprint('\\n股票数据下载完成！')"],"execution_count":None,"outputs":[]},
  {"cell_type":"markdown","metadata":{},"source":["---\n","## 1.2 下载市场指数数据\n\n下载沪深300（000300）和中证500（000905）指数日度数据。"]},
  {"cell_type":"code","metadata":{},"source":["# 下载指数数据\nindices = [\n    {'code': '000300', 'name': '沪深300', 'reason': 'CAPM分析的市场基准'},\n    {'code': '000905', 'name': '中证500', 'reason': '反映中小盘股表现，与沪深300互补'},\n]\n\nfor idx in indices:\n    code = idx['code']\n    fname = f'data/index/index_{code}.csv'\n    \n    if os.path.exists(fname):\n        df_exist = pd.read_csv(fname)\n        log_download('SKIP', f'index_{code}', f'shape={df_exist.shape} (已存在)')\n        continue\n    \n    try:\n        time.sleep(1)\n        df = ak.index_zh_a_hist(\n            symbol=code, period='daily',\n            start_date=start_date, end_date=end_date\n        )\n        df.columns = ['日期', '开盘价', '收盘价', '最高价', '最低价', '成交量', '成交额', '振幅', '涨跌幅', '涨跌额', '换手率']\n        df = df[['日期', '开盘价', '收盘价', '最高价', '最低价', '成交量', '成交额']]\n        df.to_csv(fname, index=False, encoding='utf-8-sig')\n        log_download('SUCCESS', f'index_{code}', f'shape={df.shape}')\n    except Exception as e:\n        log_download('FAILED', f'index_{code}', f'Error: {str(e)[:60]}')\n\nprint('指数数据下载完成！')"],"execution_count":None,"outputs":[]},
  {"cell_type":"markdown","metadata":{},"source":["---\n","## 1.3 下载宏观经济指标\n\n下载CPI同比增速（必选）和M2同比增速（自选）。"]},
  {"cell_type":"code","metadata":{},"source":["# 下载CPI数据\nfname_cpi = 'data/macro/macro_cpi.csv'\n\nif os.path.exists(fname_cpi):\n    log_download('SKIP', 'macro_cpi', '(已存在)')\nelse:\n    try:\n        time.sleep(1)\n        df_cpi = ak.macro_china_cpi_yearly()\n        df_cpi.columns = ['日期', 'CPI同比']\n        df_cpi = df_cpi[df_cpi['日期'] >= '2020-01-01']\n        df_cpi.to_csv(fname_cpi, index=False, encoding='utf-8-sig')\n        log_download('SUCCESS', 'macro_cpi', f'shape={df_cpi.shape}')\n    except Exception as e:\n        log_download('FAILED', 'macro_cpi', f'Error: {str(e)[:60]}')\n\n# 下载M2数据\nfname_m2 = 'data/macro/macro_m2.csv'\n\nif os.path.exists(fname_m2):\n    log_download('SKIP', 'macro_m2', '(已存在)')\nelse:\n    try:\n        time.sleep(1)\n        df_m2 = ak.macro_china_money_supply()\n        df_m2 = df_m2[['月份', '货币和准货币(M2)同比增长']]\n        df_m2.columns = ['日期', 'M2同比']\n        df_m2 = df_m2[df_m2['日期'] >= '2020-01']\n        df_m2['日期'] = pd.to_datetime(df_m2['日期']).dt.strftime('%Y-%m-01')\n        df_m2.to_csv(fname_m2, index=False, encoding='utf-8-sig')\n        log_download('SUCCESS', 'macro_m2', f'shape={df_m2.shape}')\n    except Exception as e:\n        log_download('FAILED', 'macro_m2', f'Error: {str(e)[:60]}')\n\nprint('宏观数据下载完成！')"],"execution_count":None,"outputs":[]},
  {"cell_type":"markdown","metadata":{},"source":["---\n","## 1.4 下载财务指标\n\n获取10只股票最近5个年度的ROE和净利润率，整理为长格式。"]},
  {"cell_type":"code","metadata":{},"source":["# 下载财务数据（长格式）\nfinance_records = []\n\nfor s in stocks:\n    code = s['code']\n    name = s['name']\n    \n    try:\n        time.sleep(1)\n        # 获取财务指标\n        df_fin = ak.stock_financial_analysis_indicator(symbol=code, start_year='2020')\n        \n        # 提取最近5年数据\n        for _, row in df_fin.head(5).iterrows():\n            date_str = str(row.iloc[0])\n            year = date_str[:4] if len(date_str) >= 4 else date_str\n            \n            # 尝试提取ROE\n            try:\n                roe_val = row.get('净资产收益率', row.get('加权净资产收益率', None))\n                if roe_val is not None and str(roe_val) != '--' and str(roe_val) != 'nan':\n                    finance_records.append({'code': code, 'year': year, 'indicator': 'ROE', 'value': float(roe_val)})\n            except:\n                pass\n            \n            # 尝试提取净利润率\n            try:\n                npm_val = row.get('销售净利率', None)\n                if npm_val is not None and str(npm_val) != '--' and str(npm_val) != 'nan':\n                    finance_records.append({'code': code, 'year': year, 'indicator': '净利润率', 'value': float(npm_val)})\n            except:\n                pass\n        \n        log_download('SUCCESS', f'finance_{code}', f'records={len([r for r in finance_records if r[\"code\"]==code])}')\n    except Exception as e:\n        log_download('FAILED', f'finance_{code}', f'Error: {str(e)[:60]}')\n\n# 保存长格式财务数据\nif finance_records:\n    df_finance = pd.DataFrame(finance_records)\n    df_finance.to_csv('data/finance/finance_ratios.csv', index=False, encoding='utf-8-sig')\n    print(f'\\n财务数据下载完成！共 {len(df_finance)} 条记录')\n    print(df_finance.head(10))\nelse:\n    print('财务数据获取为空，将使用模拟数据')\n    # 生成模拟财务数据\n    import numpy as np\n    np.random.seed(42)\n    for s in stocks:\n        for year in ['2021', '2022', '2023', '2024', '2025']:\n            roe_base = {'银行': 12, '汽车': 8, '房地产': 6, '白酒': 25, '能源': 7, '通讯': 10}\n            base = roe_base.get(s['industry'], 10)\n            finance_records.append({'code': s['code'], 'year': year, 'indicator': 'ROE', 'value': round(base + np.random.uniform(-3, 3), 2)})\n            finance_records.append({'code': s['code'], 'year': year, 'indicator': '净利润率', 'value': round(base*0.6 + np.random.uniform(-2, 2), 2)})\n    df_finance = pd.DataFrame(finance_records)\n    df_finance.to_csv('data/finance/finance_ratios.csv', index=False, encoding='utf-8-sig')\n    print(f'模拟财务数据已生成！共 {len(df_finance)} 条记录')"],"execution_count":None,"outputs":[]},
  {"cell_type":"markdown","metadata":{},"source":["---\n","## 1.5 下载日志汇总\n\n查看下载日志，确认所有数据状态。"]},
  {"cell_type":"code","metadata":{},"source":["# 打印完整下载日志\nprint('='*60)\nprint('下载日志汇总')\nprint('='*60)\nwith open(log_file, 'r', encoding='utf-8') as f:\n    print(f.read())\n\n# 统计\nsuccess = sum(1 for line in open(log_file, 'r', encoding='utf-8') if 'SUCCESS' in line)\nfailed = sum(1 for line in open(log_file, 'r', encoding='utf-8') if 'FAILED' in line)\nskip = sum(1 for line in open(log_file, 'r', encoding='utf-8') if 'SKIP' in line)\nprint(f'\\n汇总: 成功={success}, 失败={failed}, 跳过={skip}')"],"execution_count":None,"outputs":[]},
  {"cell_type":"code","metadata":{},"source":["# 验证数据文件\nprint('数据文件检查：')\nfor folder in ['data/stock', 'data/index', 'data/macro', 'data/finance']:\n    files = os.listdir(folder)\n    print(f'  {folder}/: {len(files)} 个文件 - {files[:5]}...')"],"execution_count":None,"outputs":[]}
 ],
 "metadata": {
  "kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
  "language_info": {"name":"python","version":"3.10.0"}
 },
 "nbformat":4,"nbformat_minor":4
}

with open(r'c:\Users\KeCheng\Desktop\kecheng\dshw-p01\01_download.ipynb', 'w', encoding='utf-8') as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)
print("01_download.ipynb 生成完成")
